### ISSUE TITLE
barteksc undefined

### ISSUE THREAD

**Issue by map7** [madmas/nativescript-pdf-view-angular-sample#2]
The error I get when running 'tns preview' I'm running nativescript 6.5.0

```
LOG from device Galaxy S8: com.tns.NativeScriptException: Error calling module function 
TypeError: Cannot read property 'barteksc' of undefined
File: (file:///data/data/org.nativescript.preview/files/app/vendor.js:280:27)

StackTrace: 
../node_modules/nativescript-pdf-view/pdf-view.js(file:///data/data/org.nativescript.preview/files/app/vendor.js:280:28)
	at __webpack_require__(file:///data/data/org.nativescript.preview/files/app/runtime.js:751:30)
	at fn(file:///data/data/org.nativescript.preview/files/app/runtime.js:121:20)
	at (file:///data/data/org.nativescript.preview/files/app/bundle.js:261:79)
	at ./main.ts(file:///data/data/org.nativescript.preview/files/app/bundle.js:326:30)
	at __webpack_require__(file:///data/data/org.nativescript.preview/files/app/runtime.js:751:30)
	at checkDeferredModules(file:///data/data/org.nativescript.preview/files/app/runtime.js:44:23)
	at webpackJsonpCallback(file:///data/data/org.nativescript.preview/files/app/runtime.js:31:19)
	at (file:///data/data/org.nativescript.preview/files/app/bundle.js:2:57)
	at require(:1:266)


TypeError: Cannot read property 'barteksc' of undefined
	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:674)
	at com.tns.Runtime.run(Runtime.java:666)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5970)
	at android.app.ActivityThread.-wrap3(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by madmas** [comment]
@map7 it looks like for some reason the underlying library to display PDFs on android (https://github.com/barteksc/AndroidPdfViewer) is not loaded properly, e.g. in 
```
pdf-view.android.ts
3:import pdfviewer = com.github.barteksc.pdfviewer;
```

I successfully tested it with Android 10 on a Pixel 3a and {N} 6.5. 
Which Android Version is your Galaxy S8 running? 
Have you also tried a `tns run android` ? Are you trying to run it with the demo app or an own app?

**Comment by map7** [comment]
I was trying this using tns preview on my Galaxy S8 running Android 7.0.

I just tried 'tns run android' running with these credentials and it was fine;

    "device.samsung": {
        "platformName": "Android",
        "platformVersion": "7.0",
        "deviceName": "samsung_galaxy_s8",
        "avd": "samsung_galaxy_s8",
        "newCommandTimeout": 720,
        "noReset": true,
        "fullReset": false,
        "app": ""
    },

Sorry about that, I shouldn't trust 'tns preview'

**Comment by madmas** [comment]
@map7 thank you for the feedback, hope nativescript-pdf-view works fine for you!
